version: '3'
services:
  db:
    image: postgres:10.0
    networks:
      - material_system_net
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: unless-stopped             # run as a service
    volumes:
      - ./material_system_db:/var/lib/postgresql/data/pgdata
  odoo:
    image: odoo:14.0
    networks:
      - material_system_net
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8071:8071"  
    tty: true
    command: -- --dev=reload
    volumes:
      - ./etc:/etc/odoo
      - ./material_system:/var/lib/odoo
      - ./custom_addons:/mnt/addons
    restart: unless-stopped             # run as a service
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - material_system_net
networks:
    material_system_net: 
        driver: bridge
volumes:
    material_system_db:
    material_system:
